export const categoriesArr = [
    "Grocery Stores",
    "Cafe and Restaurants",
    "Drug Stores and Pharmacies",
    "Entertainment",
    "Electric, Gas, Sanitary and Water Utilities",
    "Telecommunication service",
    "Automobile Parking Lots and Garages",
    "Taxi",
    "Sport",
    "Clothes and Shoes",
    "Home Supply Warehouse Stores",
    "Gadgets, Electronics and Home Appliances",
    "Kindergarten, School",
    "Education",
    "Pets",
    "Travel",
    "Duty Free",
    "Other",
    "Taxes and Fees",
    "Wire Transfer",
    "Manual Cash Disbursements",
  ];
  